#to_string.cc: enum-print.py data.hh Makefile

file(WRITE to_string.cc "// Automatically generated by make at $$(date)\n")
file(APPEND to_string.cc "// DO NOT EDIT\n")
file(APPEND to_string.cc  "#include \"internal.hh\"\n")
file(APPEND to_string.cc "DWARFPP_BEGIN_NAMESPACE\n")

execute_process(
    COMMAND	python3 ${CMAKE_CURRENT_LIST_DIR}/../elf/enum-print.py
    INPUT_FILE ${CMAKE_CURRENT_LIST_DIR}/dwarf++.hh
    OUTPUT_VARIABLE TO_STRING_OUTPUT)

file(APPEND to_string.cc "${TO_STRING_OUTPUT}\n")

execute_process(
    COMMAND	python3 ${CMAKE_CURRENT_LIST_DIR}/../elf/enum-print.py -s _ -u --hex -x hi_user -x lo_user
    INPUT_FILE ${CMAKE_CURRENT_LIST_DIR}/data.hh
    OUTPUT_VARIABLE TO_STRING_OUTPUT)

file(APPEND to_string.cc "${TO_STRING_OUTPUT}\n")

#python3 ${CMAKE_CURRENT_LIST_DIR}/../elf/enum-print.py < dwarf++.hh >> to_string.cc
#python3 ${CMAKE_CURRENT_LIST_DIR}/../elf/enum-print.py -s _ -u --hex -x hi_user -x lo_user < data.hh >> to_string.cc

file(APPEND to_string.cc "DWARFPP_END_NAMESPACE\n")
#CLEAN += to_string.cc


