#to_string.cc: enum-print.py data.hh Makefile

file(WRITE to_string.cc "// Automatically generated by make at $$(date)\n")
file(APPEND to_string.cc "// DO NOT EDIT\n")
file(APPEND to_string.cc  "#include \"data.hh\"\n")
file(APPEND to_string.cc  "#include \"to_hex.hh\"\n")
file(APPEND to_string.cc "ELFPP_BEGIN_NAMESPACE\n")
execute_process(
    COMMAND	python3 ${CMAKE_CURRENT_LIST_DIR}/enum-print.py -u --hex --no-type --mask shf --mask pf -x loos -x hios -x loproc -x hiproc 
    INPUT_FILE ${CMAKE_CURRENT_LIST_DIR}/data.hh
    OUTPUT_VARIABLE TO_STRING_OUTPUT)

file(APPEND to_string.cc "${TO_STRING_OUTPUT}\n")
file(APPEND to_string.cc "ELFPP_END_NAMESPACE\n")
#CLEAN += to_string.cc


